package com.whr.mapper;

public class SysUserRole extends SysUserRoleKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_role.sys_role_name
     *
     * @mbggenerated
     */
    private String sysRoleName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_role.sys_role_name
     *
     * @return the value of sys_user_role.sys_role_name
     *
     * @mbggenerated
     */
    public String getSysRoleName() {
        return sysRoleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_role.sys_role_name
     *
     * @param sysRoleName the value for sys_user_role.sys_role_name
     *
     * @mbggenerated
     */
    public void setSysRoleName(String sysRoleName) {
        this.sysRoleName = sysRoleName == null ? null : sysRoleName.trim();
    }
}